### ISSUE TITLE
Problem with FireFox 40.2

### ISSUE THREAD

**Issue by bollecomm** [mjolnic/fontawesome-iconpicker#13]
We have a problem with Fontawsome icon picker only in Firefox(40.0.2) .

When we have an icon picker on a page all other "Select - dropdown" are not working.

I tried at my place and i have Firfefox 39.0 (and it's working) but at work i have 40.0.2 and it's not working anymore.

I made i little index.html only with the script for the icon picker for you to see what is the problem. (The icon are not loaded but for the test it was ok!!)

http://iconpicker.bolledev.ca/

Thank you

Isabelle

**Comment by diegoag64** [comment]
I am having this same issue with Firefox 40.0.2. Hope it gets fixed soon!

**Comment by jasonmoore00** [comment]
We are also having this issue and t seems to be only on Firefox(40.0.2). When we remove the icon picker scripts, the selects work again. But when the icon picker is active, you are unable to click any of the select options in Firefox(40.0.2). 

Resolving this would be wonderful. We do appreciate your icon picker very much. Thank you.

**Comment by mjolnic** [comment]
Sorry for the late response, I see that with the latest versions it's working.
Regards
