### ISSUE TITLE
can we have a 'no-icon' option?

### ISSUE THREAD

**Issue by gmisa** [mjolnic/fontawesome-iconpicker#16]
Hi, is it possible to have an option 'no-icon' if ever the user doesn't want any?  thanks

**Comment by mjolnic** [comment]
You can always add your custom icon names using the `icons` option, so you could also append that `no-icon` to the icons list and write the proper css for that.

If the user doesn't want any icon it would be better to have the field empty and save the value as `null`, anyway.
