### ISSUE TITLE
Empty Fields

### ISSUE THREAD

**Issue by WS-Theme** [mjolnic/fontawesome-iconpicker#2]
Hi there,

I have build up a Form Field for Joomla with this fantastic Plugin, but unfortunatelly there are at the end a lot of empty fields ...

Example:

    <div class="iconpicker-item" title=".fa-align-right">
    <div class="iconpicker-item" title=".fa-ambulance">
    <div class="iconpicker-item" title=".fa-function (){return h}">
    <div class="iconpicker-item" title=".fa-function Array() { [native code] }">
    <div class="iconpicker-item" title=".fa-function (b,a){Array.forEach(this,b,a);return this}">
    <div class="iconpicker-item" title=".fa-function (){for(var b=this.length, a=Array(b);b--;)a[b]=q(this[b]);return a}">
    <div class="iconpicker-item" title=".fa-function (){return this.filter(function(b){return null!=b})}">
    <div class="iconpicker-item" title=".fa-function (b){var a=Array.slice(arguments,1);return this.map(function(c){return c[b].apply(c,a)})}">
    <div class="iconpicker-item" title=".fa-function (b){for(var a={},c=Math.min(this.length,b.length),d=0;d<c;d++)a[b[d]]=this[d];return a}">
    <div class="iconpicker-item" title=".fa-function (b){for(var a={},c=0,d=this.length;c<d;c++)for(var e in b)if(b[e](this[c])){a[e]=this[c];delete b[e];break}return a}">
    <div class="iconpicker-item" title=".fa-function (b,a){return-1!=this.indexOf(b,a)}">
    <div class="iconpicker-item" title=".fa-function (b){this.push.apply(this,b);return this}">
    <div class="iconpicker-item" title=".fa-function (){return this.length?this[this.length-1]:null}">
    <div class="iconpicker-item" title=".fa-function (){return this.length?this[Number.random(0,this.length-1)]:null}">
    <div class="iconpicker-item" title=".fa-function (b){this.contains(b)||this.push(b);return this}">
    <div class="iconpicker-item" title=".fa-function (b){for(var a=0,c=b.length;a<c;a++)this.include(b[a]);return this}">``

As you see, above is all ok, then it starts with some functions, but not sure why! Maybe you have a Solution??

Cheers, Oli

**Comment by mjolnic** [comment]
Hi @WS-Theme it seems something related to Joomla and other plugins you may have there. I don't understand what do you mean by empty fields? .fa-function is not a Fontawesome icon and is not in the iconpicker source code, so definitely is something related to your code.

**Comment by WS-Theme** [comment]
All right, was only aquestion if you maybe had a hint or similar where this comes from! Thanks!
