### ISSUE TITLE
Would be great if it also displayed the Unicode for each icon

### ISSUE THREAD

**Issue by adamevosite** [mjolnic/fontawesome-iconpicker#20]
Hi,

This is a great idea and will be helpful when working on web projects but we also need the unicode when building sites and it would be really helpful if it could also display this when an icon is selected.

Thanks
Adam

**Comment by mjolnic** [comment]
Hi, you can actually copy the Unicode character by selecting the icon text between quotes and copying it:


![captura de pantalla 2016-06-25 15 15 09](https://cloud.githubusercontent.com/assets/122741/16356906/b632c542-3ae7-11e6-9ae4-54f66697dec9.png)

**Comment by adamevosite** [comment]
Ah, sorry. Didn't realise, awesome work!
