### ISSUE TITLE
Example for custom fonts set needed

### ISSUE THREAD

**Issue by DemarsM** [mjolnic/fontawesome-iconpicker#3]
I would appreciate an example using custom fonts set. I encounter some problems with missing reference to .fa class when I set the default options like those:

    iconBaseClass: "",
    iconComponentBaseClass: "",
    iconClassPrefix: "",

Then I create instance like that:

    <style>
        .marker-airfield:before { content: url("/media/airfield.svg"); }
    </style>
    
    <input id="marker" class="textinput textInput form-control" type="text" name="form-0-marker">
    
    $("#marker").iconpicker({
        icons: ['marker-airfield']
    });

I got this error:
Error: Syntax error, unrecognized expression: .fa.

**Comment by mjolnic** [comment]
Hi @DemarsM which version of jQuery are you using? This library is only tested with 1.x
If you read the README you will see the list of available options. The ones you specified does not exist.

Maybe you may provide your own fullClassFormatter method in the options, just returning the val itself.
