### ISSUE TITLE
Dropdown doesn't get populated.

### ISSUE THREAD

**Issue by Syrah-NL** [mjolnic/fontawesome-iconpicker#5]
Hi, I'm trying to get a dropdown font-awesome picker to work on my website, like your $('.icp-dd') example. It doesn't work for me however. Even when I copy the exact source code from your example (including the bootstrap version, and the fontawesome-iconpicker etc etc), all examples work, except the dropdown ones.

Here, I copied your entire source code, and the dropdowns don't work:

http://www.webl.es/skyline2/fontawesomepicker.html

Can you help me?

**Comment by mjolnic** [comment]
Hi @Syrah-NL  you are not using the same source code https://www.diffchecker.com/dx4vasaj

**Comment by Syrah-NL** [comment]
What the...?! I copied it straight from the view-source: page... Weird! 
I now use bootstrap iconpicker though, which works just as well and supports other icon packs such as glyphicon as well. Thanks for the reply.
