### ISSUE TITLE
JavaScript error: Cannot read property 'nodeType' of undefined

### ISSUE THREAD

**Issue by MickeyKay** [mjolnic/fontawesome-iconpicker#7]
I'm getting the following JS error and can't for the life of me figure out why:

```
Uncaught TypeError: Cannot read property 'nodeType' of undefined
```

According to dev tools, the issue is arising on line 12 of fontawesome-iconpicker.js (occurs on the minified version as well.

Here's my HTML:
```
<a href="#" class="fontawesome-iconpicker button-primary"><span class="fa fa-flag"></span></a>
```

And here's my JS:
```
$( document ).ready( function() {
	$('.fontawesome-iconpicker').iconpicker();
});
```
This issue goes away if I switch from an `<a>` element to using an `<input>` - is that the issue? If so, I'd love to be able to use any element I want - maybe I'm just missing some setting I need to edit.

I can't for the life of me figure out why this is happening, any ideas? Thanks!

**Comment by mjolnic** [comment]
Hi @MickeyKay I cannot reproduce that error, could you provide an online example? which version of jQuery are you using?
Try using this syntax or similar: http://jsfiddle.net/spqc7zub/1/

Cheers

**Comment by MickeyKay** [comment]
Currently I'm developing in a local WordPress instance, so there's no good way to share. I did try your exact code though, and I still get the same error. . .

I *did* notice that you're using jQuery 2.1.3 in your fiddle, however WP includes on jQuery 1.11.2 at this point. Even if you try using your code with jQuery set to version 1.6.4, it fails, although seemingly for a different reason: http://jsfiddle.net/spqc7zub/2/

The errors I get with this version of jQuery aren't even the same ones I'm experiencing in the WP install, however they may indicate that your library doesn't work on older versions of jQuery. If this is the case, then you may want to consider more backwards compatibility - if I'm correct (and it may still be my error), then this won't work in default WP at this point.

**Comment by mjolnic** [comment]
@MickeyKay That's weird, maybe you have some other script that is causing that problem, the plugin is compatible from jQuery version 1.7.2 and onwards as you can see: http://jsfiddle.net/spqc7zub/3/ (also tested in 1.11.0)

I also used exactly your code, but I am not having your JS error (and any error), only that the picker wasn't working properly (cause it needed a different syntax like I posted).

It's not in my plans to bring backwards compatibility to prior versions ;) , 1.6.x is 4 years old, that would only add more unnecessary overhead to the plugin.

**Comment by MickeyKay** [comment]
That all sounds good to me - definitely agree that there's no need to go so far with backwards compatibility. I'll work on debugging further to see what's up. Thanks!

**Comment by MickeyKay** [comment]
Ahhh - I figured it out. The problem is that your site's download button (http://mjolnic.com/fontawesome-iconpicker/) is linking to an archive of release 1.0.0, which doesn't work properly. I re-downloaded via git and things are working now. You should definitely update that link to point to the latest release, or ideally just to master, assuming that branch stays stable and you've got a dev branch you're working on. Man, that seriously took me like 5 hours to figure out today what was going on. Errrrg.

Also, it's great that you include minified/uglified .js, however I noticed that your "non-minified" .js file is still uglified (e.g. function name simplified to one-letter name). This makes debugging almost impossible, and it'd be great if you could include the fully un-uglified source for testing.

**Comment by mjolnic** [comment]
@MickeyKay I am sorry to hear that, but since I am the only developer for now in this project It is very common to have mistakes, we are humans ;).

Thanks for reporting, I will try to fix that when possible. Anyway, any PRs will be also welcome. I always try to encourage people to collaborate, cause that's the main purpose of Open source code, right? =)
